INSERT INTO committee VALUES(
'NAME OF COMMITTEE', 'DESCRIPTION');

INSERT INTO committee seat VALUES(
'DESCRIPTION', 'STARTING TERM', 'ENDING TERM', 'CHAIRMAN', 'USER CNU ID');

INSERT INTO election VALUES(
'STATUS', 'TERM ID');

INSERT INTO committee VALUES(
'NAME OF COMMITTEE', 'DESCRIPTION');

INSERT INTO user VALUES(
'CNU ID', 'NAME', 'DEPARTMENT', 'POSITION', 'BIRTHDAY', 'DATE OF HIRING', 
'GENDER', 'RACE');